#home
#spring:
#  datasource:
#    data-username: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://192.168.0.111:3306/sell?characterEncoding=utf-8&useSSL=false
#    password: 123456
#  jpa:
#    show-sql: true

#company
spring:
  datasource:
    data-username: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
    password:
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /sell
  port: 8081
